import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const files = {
  "index.html": "text/html",
  "style.css": "text/css",
  "app.js": "text/javascript",
  "sw.js": "text/javascript",
};

let out = "// AUTO-GENERATED by scripts/build-assets.mjs — do not edit directly.\n";
out += "// This keeps the frontend embedded so every target (Node/Workers/Vercel/Docker) serves it identically.\n\n";

for (const [name, type] of Object.entries(files)) {
  const content = await readFile(resolve(root, "public", name), "utf8");
  const key = name.replace(/\W/g, "_");
  out += `export const ${key} = ${JSON.stringify(content)};\n`;
}

out += "\nexport const assetContentTypes = " + JSON.stringify(files, null, 2) + ";\n";

await mkdir(resolve(root, "src"), { recursive: true });
await writeFile(resolve(root, "src", "assets.ts"), out);
console.log("[build-assets] wrote src/assets.ts (" + out.length + " bytes)");

// Also inline the two WebP WASM files so `tsx`/`node dist` never needs to
// resolve a `.wasm` import at runtime.
const dec = await readFile(resolve(root, "node_modules/@jsquash/webp/codec/dec/webp_dec.wasm"));
const enc = await readFile(resolve(root, "node_modules/@jsquash/webp/codec/enc/webp_enc.wasm"));
const wasmOut =
  "// AUTO-GENERATED by scripts/build-assets.mjs — do not edit directly.\n" +
  `export const webpDecWasmBase64 = ${JSON.stringify(dec.toString("base64"))};\n` +
  `export const webpEncWasmBase64 = ${JSON.stringify(enc.toString("base64"))};\n`;
await writeFile(resolve(root, "src", "webp-wasm.ts"), wasmOut);
console.log("[build-assets] wrote src/webp-wasm.ts");